In [ ]:
# import numpy
import numpy as np
x =np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
%timeit [i**2 for i in range(1,9)]

2.52 µs ± 49.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**2

1.46 µs ± 187 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# creating list/array 2D 3D OR MULTIDIMENSIONAL ARRAY
l = []

for i in range(1,5):
  x = int(input("enter: "))
  l.append(x)
print(np.array(l))

enter: 1
enter: 2
enter: 3
enter: 4
[1 2 3 4]


In [ ]:
x =np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(x)
print(x.ndim)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
2


In [ ]:
x =np.array([[[1,2,3],[3,2,1],[4,5,6]]])
print(x)
print(x.ndim)

[[[1 2 3]
  [3 2 1]
  [4 5 6]]]
3


In [ ]:
x=np.array([1,2,3], ndmin=10)
print(x)
print(x.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [ ]:
import numpy as np
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,3))
print(arr_zero)
print()
print(arr_zero1)
print(arr_zero1.ndim)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [ ]:
arr_one = np.ones(4)
arr_one1 = np.ones((3,4))
print(arr_one)
print(arr_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# indetity/diagonal matrix
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_empty = np.empty(3)
print(arr_empty)

[1. 1. 1.]


In [ ]:
# create numpy array
import numpy as np
var = np.random.rand(4)
print(var)

[0.96295713 0.43408303 0.06830441 0.24302388]


In [ ]:
var1 = np.random.rand(2,5)
print(var1)

[[0.90641698 0.1068386  0.35995857 0.44622999 0.03360434]
 [0.33669904 0.53837477 0.08276239 0.24639535 0.14200995]]


In [ ]:
var2= np.random.randn(3)
var3=np.random.randn(2,3)
print(var3)
print(var2)

[[ 1.93407147  0.96341285 -1.24983521]
 [-0.15739639 -0.61280417 -0.774622  ]]
[-0.08501797  0.77206868  1.08879422]


In [ ]:
var4 = np.random.ranf(3)
print(var4)

[0.68229301 0.71378406 0.50718576]


In [ ]:
var = np.random.randint(1,100,5)
print(var)
print(var.ndim)

[98 84 23 55 18]
1
[22 15 87 56 73]
1


In [ ]:
# datatypes in numpy array
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var.dtype, ": DATATYPE")
print(var.ndim)

int64 : DATATYPE
1


In [ ]:
# Changing datatype in numpy array
var = np.array([1,2,3,4,5,6], dtype=np.int8)
print(var.dtype, ": DATATYPE")


int8 : DATATYPE


In [ ]:
var = np.array([1,2,3,4,5,6], dtype='f')
print(var.dtype, ": DATATYPE")
print(var)

float32 : DATATYPE
[1. 2. 3. 4. 5. 6.]


In [ ]:
var = np.array([1,2,3,4,5,6])
new=np.float32(var)
new1=np.int32(new)
print(var.dtype, ": DATATYPE")
print(var)
print(new)
print("datatype: ",new.dtype )
print(new1)
print("datatype: ", new1.dtype)

int64 : DATATYPE
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
datatype:  float32
[1 2 3 4 5 6]
datatype:  int32


In [ ]:
# arthimetic in numpy
var= np.array([1,2,3,4,5])
var1=np.array([1,2,3,4,5])
add= var+var1
print(var)
print(add)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [42]:
# Arithimatic Operations
var = np.array([1,2,3,4,5,6,7])
print("min: ", np.min(var))
print("max: ", np.max(var))
print("Min position: ", np.argmin(var))
print("Max position: ", np.argmax(var))

min:  1
max:  7
position:  0
position:  6


In [51]:
var = np.array([[1,2,3],[5,6,7]])
print(np.min(var,axis=1)) #1 for Rows
print(np.min(var,axis=0)) #0 for Columns
print(np.sqrt(var))

[1 5]
[1 2 3]
[[1.         1.41421356 1.73205081]
 [2.23606798 2.44948974 2.64575131]]


In [53]:
# Trignometry in numpy
var=np.array([1,2,3])
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [55]:
# Shape and reshape of array
var = np.array([[1,2,3],[9,8,7]])
print(var)
print(np.shape(var))

[[1 2 3]
 [9 8 7]]
(2, 3)


In [77]:
var = np.array([[1,2,3,4,5,6,7,8]])
print(var)
print(np.shape(var))
x = var.reshape(4,2)
y = var.reshape(2,2,2)
print(x)
print()
print(y)

one = var.reshape(-1)
print(one)
print(y.ndim)

[[1 2 3 4 5 6 7 8]]
(1, 8)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
3


In [6]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dal\\Downloads\\test.csv'