In [30]:
import cv2
import numpy as np
import os

In [29]:
import cv2
img1 = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
img2 = cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
re_img1 =cv2.resize(img1,(500,700)) 

cv2.imshow("zzz",img1)
cv2.imshow("zzz",re_img1)
cv2.imshow("zzx",img2)
cv2.waitKey(0)

cv2.destroyAllWindows()


In [21]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [83]:
v = np.array([[1,2,3,1,2,3],[1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [82]:
img1 = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
print(img) #RGB 

[[[30 55 71]
  [21 46 62]
  [13 38 54]
  ...
  [36 69 89]
  [29 61 84]
  [29 61 84]]

 [[27 52 68]
  [23 48 64]
  [20 45 61]
  ...
  [29 62 82]
  [29 61 84]
  [37 69 92]]

 [[25 50 66]
  [25 50 66]
  [23 48 64]
  ...
  [39 70 91]
  [37 68 91]
  [37 68 91]]

 ...

 [[24 51 71]
  [31 58 78]
  [37 64 84]
  ...
  [33 68 88]
  [32 67 87]
  [30 67 87]]

 [[25 52 72]
  [32 59 79]
  [38 65 85]
  ...
  [33 68 88]
  [30 67 87]
  [30 67 87]]

 [[25 54 75]
  [32 61 82]
  [38 68 87]
  ...
  [33 67 90]
  [30 67 89]
  [30 67 89]]]


In [88]:
import cv2
import numpy as np
img1 = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
img2 = cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
re_img =cv2.resize(img1,(300,500)) 
h = np.hstack((re_img,re_img))
g = np.vstack((re_img,re_img))
# cv2.imshow("zzz",img1)
cv2.imshow("zzz",h)
cv2.imshow("zzr",g)
# cv2.imshow("zzx",img2)
# cv2.waitKey(1000)
cv2.waitKey(0)
# cv2.destroyAllWindows()
cv2.destroyAllWindows()

In [129]:
import cv2
import numpy as np
img1 = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
img2 = cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")

re_img =cv2.resize(img1,(300,350)) 
h = np.hstack((re_img,re_img,re_img,re_img))
g = np.vstack((h,h))
cv2.imshow("zzz",g)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
list_name = os.listdir(r"C:\Users\dal\Downloads\zzm") #OS library used
list_name

['download.jpg', 'Wallpaper Zoro One Piece.jpg']

In [81]:
for name in list_name:
    path = "C:\\Users\\dal\\Downloads\\zzm"
    img_name =  path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(500,600))
    cv2.imshow("Rahul",img)
    # cv2.waitKey(1000)
    cv2.waitKey(0)
cv2.destroyAllWindows()

In [78]:
import cv2
import numpy as np
img = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg",0)
resize_img = cv2.resize(img,(400,600))
cv2.imshow("System",resize_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img.shape)

(1019, 720)


In [127]:
import cv2
import numpy as np
img = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg",1)
resize_img = cv2.resize(img,(400,600))
cv2.imshow("System",resize_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img.shape)

(1019, 720, 3)


In [76]:
import cv2
import numpy as np
img = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg",-1)
resize_img = cv2.resize(img,(400,600))
cv2.imshow("System",resize_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img.shape)

(1019, 720, 3)


In [27]:
#Text over image
import cv2
img_get = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
re_img = cv2.resize(img_get,(450,600))


txt = cv2.putText(img = re_img,
text = "ZORO",
org = (90,80),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color = (0,0,255),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = False)

txt = cv2.putText(img = re_img,
text = "ZORO",
org = (90,90),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color = (0,0,255),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = True)


cv2.imshow("rahul",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [42]:
#Line and Box to an image
import cv2
old_img = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
old_img = cv2.resize(old_img,(300,500))

new_img = cv2.line(img = old_img, pt1=(50,120), pt2=(250,120), color=(0,0,255), thickness=4,lineType=4)

cv2.imshow("Nitsss",old_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
#Line and Box to an image
import cv2
old_img = cv2.imread(r"C:\Users\dal\Downloads\zzm\download.jpg")
old_img = cv2.resize(old_img,(300,500))

new_img = cv2.rectangle(img = old_img, pt1=(50,100), pt2=(250,320), color=(0,0,255), thickness=4,lineType=16)

txt = cv2.putText(img = old_img,
text = "ZORO",
org = (45,80),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale = 1,
color = (0,0,255),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = False)

#Inverted Text//

# txt = cv2.putText(img = old_img,
# text = "ZORO",
# org = (30,90),
# fontFace = cv2.FONT_HERSHEY_DUPLEX,
# fontScale = 3,
# color = (0,0,255),
# thickness = 3,
# lineType = cv2.LINE_8,
# bottomLeftOrigin = True)

cv2.imshow("Nitsss",old_img)
cv2.imshow("Nitsss",old_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# Circle and Ellipse on Image
import cv2
img2 = cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
re_img =cv2.resize(img2,(300,500)) 

# CIRCLE 
img_cir = cv2.circle(img = re_img, center = (140,250), radius=70, color=(500,200,255), thickness=8, lineType=16)
# ELLIPSE
img_elp = cv2.ellipse(img =img_cir,center = (140,250),axes =(50,100),angle=0,startAngle =0,endAngle=360,color=(0,0,255),thickness=8,lineType=16)
cv2.imshow("zzz",img_elp)
cv2.imshow("zzz",img_cir)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
import cv2
import numpy as np

img2 = cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
re_img =cv2.resize(img2,(300,500)) 

new_img = cv2.polylines(img = re_img, pts = [np.array([[100,200],[50,350],[300,300],[200,100],[180,200]])], isClosed = True, 
                        color = (0,0,255), thickness=4,lineType=16)
cv2.imshow("qq",new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
#BLuring on Images

img=cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
resize_img=cv2.resize(img,(300,500))

A = cv2.GaussianBlur(resize_img,(7,7),0)
B = cv2.medianBlur(resize_img,3)
D = cv2.bilateralFilter(resize_img,9,75,75)

C = np.hstack((resize_img,A,B,D))

cv2.imshow("A",C)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
#imwrite function in OpenCV (to save edited images)
import cv2
import numpy as np
img=cv2.imread(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg")
resize_img=cv2.resize(img,(300,500))
A = resize_img

h = np.hstack((A,A,A))
v = np.vstack((h,h))

cv2.imwrite(r"C:\Users\dal\Downloads\zzm\Wallpaper Zoro One Piece.jpg",v)
cv2.imshow("A",v)

cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
